// Assembles the sdk-sync pipeline's PR title/body/labels from the three structured
// files earlier jobs produced (sync-summary.json, verify-results.json,
// docs-parity-results.json), instead of scraping free-text agent output. Writes
// pr-body.md plus pr-meta.json ({ title, needsAttention }) for the open-pr job's
// gh pr create/edit step to read.
import fs from "node:fs";
import path from "node:path";

const readJson = (filePath, fallback) => {
  if (!fs.existsSync(path.resolve(filePath))) {
    return fallback;
  }
  return JSON.parse(fs.readFileSync(path.resolve(filePath), "utf8"));
};

const summary = readJson(process.env.SDK_SYNC_SUMMARY_PATH ?? "sync-summary.json", null);
const verify = readJson(process.env.SDK_SYNC_VERIFY_RESULTS_PATH ?? "verify-results.json", { lanes: [] });
const docsParity = readJson(
  process.env.SDK_SYNC_DOCS_RESULTS_PATH ?? "docs-parity-results.json",
  { checked: 0, passed: 0, failed: [] },
);

const lanesTable = () => {
  if (verify.lanes.length === 0) {
    return "_No verify lanes ran._";
  }

  const rows = verify.lanes.map((lane) => {
    const status = lane.skipped ? "skipped (no conformance secrets yet)" : lane.ok ? "pass" : "**fail**";
    return `| ${lane.name} | ${status} |`;
  });

  return ["| Lane | Result |", "| --- | --- |", ...rows].join("\n");
};

const docsParitySection = () => {
  if (docsParity.checked === 0) {
    return "_No operations required a doc-parity check this run._";
  }

  const lines = [`${docsParity.passed}/${docsParity.checked} touched operations have matching tags/examples in every expected language.`];

  if (docsParity.failed.length > 0) {
    lines.push("", "Flagged:");
    for (const failure of docsParity.failed) {
      lines.push(`- \`${failure.sdkOperation}\` (${failure.jsSdkSymbol}): ${failure.reasons.join("; ")}`);
    }
  }

  return lines.join("\n");
};

const symbolsSection = () => {
  if (!summary || summary.symbols.length === 0) {
    return "_No symbols reported._";
  }

  return summary.symbols
    .map((s) => `- \`${s.sdkOperation}\` (${s.jsSdkSymbol}) - ${s.change}, python: ${s.dispositions?.python ?? "?"}, csharp: ${s.dispositions?.csharp ?? "?"}`)
    .join("\n");
};

const verifyFailed = verify.lanes.some((lane) => lane.ok === false);
const docsFailed = docsParity.failed.length > 0;
const agentBlockers = summary?.blockers ?? [];
const missingSummary = !summary;

const needsAttention = verifyFailed || docsFailed || agentBlockers.length > 0 || missingSummary;

const title = `sdk-sync: port js-sdk changes to Python/C# (${summary?.symbols?.length ?? 0} operations)`;

const body = `## What this is

Automated port of a \`packages/js-sdk\` change into \`sdks/python\` and \`sdks/csharp\`, generated by the sdk-sync pipeline. Nothing here has been merged or published; this PR needs human review before it lands. See \`packages/conformance/docs/sdk-sync-agent.md\` for how this pipeline works and how to fix or re-run it.

${needsAttention ? "**This PR is flagged: something below needs a human look before merging.**" : "Everything below came back clean."}

## Summary

${summary?.summary ?? "_The generation agent did not produce sync-summary.json for this run - check the generate job logs._"}

## Symbols touched

${symbolsSection()}

## Verify (lint / build / test / conformance)

${lanesTable()}

## Doc tag / example parity

${docsParitySection()}

## Agent-reported blockers

${agentBlockers.length > 0 ? agentBlockers.map((b) => `- ${b}`).join("\n") : "_None reported._"}

## Reviewer checklist

- [ ] New/changed \`sdks/parity/dispositions.json\` entries look right
- [ ] Any new \`sdks/WIRE-NOTES.md\` entries reflect the real API behavior, not just js-sdk's doc comments
- [ ] Any failed or skipped lane above is understood before merging
- [ ] The changeset (if any) bumps the right package at the right level
`;

fs.writeFileSync("pr-body.md", body);
fs.writeFileSync("pr-meta.json", `${JSON.stringify({ title, needsAttention }, null, 2)}\n`);

console.log(`Wrote pr-body.md and pr-meta.json (needsAttention: ${needsAttention})`);
