"""Color helpers (verdocs.utils.colors).

Expected strings were generated by running the js-sdk Utils/Colors.ts logic
verbatim under Node, so these tests pin byte-for-byte parity, including the
number quirks (round-half-up, 32-bit hash wrap, truncated modulo).
"""

from __future__ import annotations

import pytest

from verdocs.utils import get_rgb, get_rgba, get_role_color, name_to_rgba


@pytest.mark.parametrize(
    ("rgba", "expected"),
    [
        ("rgba(255, 193, 7, 0.4)", "#ffe69c"),
        # The js-sdk source comments claim #E3C3E9 / #C1E1FB for the next two;
        # the code computes these values instead. We match the code.
        ("rgba(156, 39, 176, .4)", "#d7a9df"),
        ("rgba(33, 150, 243, .4)", "#a6d5fa"),
        ("rgba(220, 231, 117, 0.3)", "#f4f8d6"),
        ("rgba(2, 247, 190, 0.3)", "#b3fdeb"),
        ("rgba(0, 0, 0, 1)", "#000000"),
        ("rgba(255, 255, 255, 0)", "#ffffff"),
        ("rgba(12, 34, 56, 0.5)", "#86919c"),
    ],
)
def test_get_rgb(rgba: str, expected: str):
    assert get_rgb(rgba) == expected


@pytest.mark.parametrize(
    ("index", "expected"),
    [
        (0, "rgba(255, 193, 7, 0.4)"),
        (1, "rgba(156, 39, 176, .4)"),
        (2, "rgba(33, 150, 243, .4)"),
        (3, "rgba(220, 231, 117, 0.3)"),
        (4, "rgba(121, 134, 203, 0.3)"),
        (5, "rgba(77, 182, 172, 0.3)"),
        (6, "rgba(255, 202, 165, 0.3)"),
        (7, "rgba(2, 247, 190, 0.3)"),
        (8, "rgba(255, 138, 101, 0.3)"),
        (9, "rgba(82, 255, 79, 0.3)"),
        # Index 10 wraps to the remainder-0 case but is not index 0, so it
        # gets gray rather than the first signer's yellow.
        (10, "rgba(134, 134, 134, 0.3)"),
        (11, "rgba(156, 39, 176, .4)"),
        (23, "rgba(220, 231, 117, 0.3)"),
        # JS % truncates toward zero, so a negative index matches no case and
        # lands on the default color.
        (-1, "rgba(229, 115, 155, 0.3)"),
    ],
)
def test_get_rgba(index: int, expected: str):
    assert get_rgba(index) == expected


@pytest.mark.parametrize(
    ("name", "expected"),
    [
        ("Recipient 1", "rgba(118, 200, 8, 0.2)"),
        ("Recipient 2", "rgba(39, 131, 8, 0.2)"),
        ("Owner", "rgba(131, 61, 8, 0.2)"),
        ("Approver", "rgba(58, 234, 8, 0.2)"),
        ("Signer", "rgba(158, 30, 0, 0.2)"),
        ("A", "rgba(0, 0, 0, 0.2)"),
        ("Role 10", "rgba(190, 120, 0, 0.2)"),
        ("countersigner", "rgba(70, 67, 8, 0.2)"),
    ],
)
def test_name_to_rgba(name: str, expected: str):
    assert name_to_rgba(name) == expected


def test_name_to_rgba_is_stable():
    assert name_to_rgba("Recipient 1") == name_to_rgba("Recipient 1")


def test_name_to_rgba_empty_name():
    # The js-sdk implicitly returns undefined for a falsy name.
    assert name_to_rgba("") is None
    assert name_to_rgba(None) is None


def test_get_role_color_prefers_explicit_index():
    assert get_role_color("Owner", [], 3) == "rgba(220, 231, 117, 0.3)"


def test_get_role_color_index_zero_falls_through():
    # js checks `if (index)`, so 0 is treated as absent and the roles lookup
    # answers instead. Quirk kept.
    assert get_role_color("Recipient 1", ["Recipient 1"], 0) == "rgba(255, 193, 7, 0.4)"


def test_get_role_color_uses_position_in_roles():
    roles = ["Recipient 1", "Recipient 2"]
    assert get_role_color("Recipient 1", roles) == "rgba(255, 193, 7, 0.4)"
    assert get_role_color("Recipient 2", roles) == "rgba(156, 39, 176, .4)"


def test_get_role_color_falls_back_to_name_hash():
    assert get_role_color("Missing", ["Recipient 1"]) == "rgba(91, 157, 8, 0.2)"
    assert get_role_color("Owner", []) == "rgba(131, 61, 8, 0.2)"
    assert get_role_color("Owner", None) == "rgba(131, 61, 8, 0.2)"
