"""String helpers (verdocs.utils.strings).

The convert_to_e164 expectations were generated by running the js-sdk logic
under Node, so they pin byte-for-byte parity.
"""

from __future__ import annotations

import pytest

from verdocs.utils import capitalize, convert_to_e164, random_string

_BASE36 = set("0123456789abcdefghijklmnopqrstuvwxyz")


def test_capitalize():
    assert capitalize("test") == "Test"
    assert capitalize("hello world") == "Hello world"
    assert capitalize("a") == "A"
    assert capitalize("") == ""


@pytest.mark.parametrize(
    ("value", "expected"),
    [
        ("(212) 555-1212", "+12125551212"),
        ("212-555-1212", "+12125551212"),
        ("212.555.1212", "+12125551212"),
        ("212 555 1212", "+12125551212"),
        # A "+" prefix short-circuits: trimmed but otherwise untouched.
        ("+46766861004", "+46766861004"),
        ("  +44 20 7946  ", "+44 20 7946"),
        # One leading zero comes off, wherever punctuation hid it.
        ("0(5) 123-4567", "+151234567"),
        ("(05) 123-4567", "+151234567"),
        # Only the first zero: the js regex anchors at the string start.
        ("0012", "+1012"),
        ("", ""),
        (None, ""),
        ("   ", ""),
    ],
)
def test_convert_to_e164(value: str | None, expected: str):
    assert convert_to_e164(value) == expected


def test_random_string_length_and_alphabet():
    # Adapted: exactly the requested length (the js-sdk's substring bounds
    # return length + 1 characters) and secrets-backed randomness.
    for length in (1, 4, 8, 32):
        value = random_string(length)
        assert len(value) == length
        assert set(value) <= _BASE36
    assert random_string(0) == ""


def test_random_string_varies():
    assert random_string(16) != random_string(16)
