using Verdocs.Utils;
using Xunit;

namespace Verdocs.Sdk.Tests;

/// <summary>
/// String helpers (Verdocs.Utils.Strings). The ConvertToE164 expectations were generated by
/// running the js-sdk logic under Node (shared with the Python SDK's tests), so they pin
/// byte-for-byte parity.
/// </summary>
public sealed class UtilsStringsTests
{
    private const string Base36Alphabet = "0123456789abcdefghijklmnopqrstuvwxyz";

    [Theory]
    [InlineData("test", "Test")]
    [InlineData("hello world", "Hello world")]
    [InlineData("a", "A")]
    [InlineData("", "")]
    public void Capitalize_Input_UppercasesFirstLetterOnly(string value, string expected)
    {
        Assert.Equal(expected, Strings.Capitalize(value));
    }

    [Theory]
    [InlineData("(212) 555-1212", "+12125551212")]
    [InlineData("212-555-1212", "+12125551212")]
    [InlineData("212.555.1212", "+12125551212")]
    [InlineData("212 555 1212", "+12125551212")]
    // A "+" prefix short-circuits: trimmed but otherwise untouched.
    [InlineData("+46766861004", "+46766861004")]
    [InlineData("  +44 20 7946  ", "+44 20 7946")]
    // One leading zero comes off, wherever punctuation hid it.
    [InlineData("0(5) 123-4567", "+151234567")]
    [InlineData("(05) 123-4567", "+151234567")]
    // Only the first zero: the js regex anchors at the string start.
    [InlineData("0012", "+1012")]
    [InlineData("", "")]
    [InlineData(null, "")]
    [InlineData("   ", "")]
    public void ConvertToE164_PhoneNumberLikeInput_MatchesJsSdk(string? value, string expected)
    {
        Assert.Equal(expected, Strings.ConvertToE164(value));
    }

    [Fact]
    public void RandomString_RequestedLength_UsesBase36Alphabet()
    {
        // Adapted: exactly the requested length (the js-sdk's substring bounds return
        // length + 1 characters) and a cryptographic RNG.
        foreach (var length in new[] { 1, 4, 8, 32 })
        {
            var value = Strings.RandomString(length);
            Assert.Equal(length, value.Length);
            Assert.All(value, ch => Assert.Contains(ch, Base36Alphabet));
        }

        Assert.Equal("", Strings.RandomString(0));
    }

    [Fact]
    public void RandomString_TwoCalls_Vary()
    {
        Assert.NotEqual(Strings.RandomString(16), Strings.RandomString(16));
    }
}
