using Verdocs.Utils;
using Xunit;

namespace Verdocs.Sdk.Tests;

/// <summary>
/// Pins Verdocs.Utils.Colors to the js-sdk Utils/Colors.ts outputs. The expected strings were
/// generated by running the js logic under Node and are shared with the Python SDK's tests, so
/// all three implementations pin byte-for-byte parity, including the number quirks
/// (round-half-up, 32-bit hash wraparound, truncated modulo).
/// </summary>
public sealed class UtilsColorsTests
{
    [Theory]
    [InlineData("rgba(255, 193, 7, 0.4)", "#ffe69c")]
    // The js-sdk source comments claim #E3C3E9 / #C1E1FB for the next two; the code computes
    // these values instead. We match the code.
    [InlineData("rgba(156, 39, 176, .4)", "#d7a9df")]
    [InlineData("rgba(33, 150, 243, .4)", "#a6d5fa")]
    [InlineData("rgba(220, 231, 117, 0.3)", "#f4f8d6")]
    [InlineData("rgba(2, 247, 190, 0.3)", "#b3fdeb")]
    [InlineData("rgba(0, 0, 0, 1)", "#000000")]
    [InlineData("rgba(255, 255, 255, 0)", "#ffffff")]
    [InlineData("rgba(12, 34, 56, 0.5)", "#86919c")]
    public void GetRgb_RgbaString_ReturnsHexCompositedAgainstWhite(string rgba, string expected)
    {
        Assert.Equal(expected, Colors.GetRgb(rgba));
    }

    [Theory]
    [InlineData(0, "rgba(255, 193, 7, 0.4)")]
    [InlineData(1, "rgba(156, 39, 176, .4)")]
    [InlineData(2, "rgba(33, 150, 243, .4)")]
    [InlineData(3, "rgba(220, 231, 117, 0.3)")]
    [InlineData(4, "rgba(121, 134, 203, 0.3)")]
    [InlineData(5, "rgba(77, 182, 172, 0.3)")]
    [InlineData(6, "rgba(255, 202, 165, 0.3)")]
    [InlineData(7, "rgba(2, 247, 190, 0.3)")]
    [InlineData(8, "rgba(255, 138, 101, 0.3)")]
    [InlineData(9, "rgba(82, 255, 79, 0.3)")]
    // Index 10 wraps to the remainder-0 case but is not index 0, so it gets gray rather than
    // the first signer's yellow.
    [InlineData(10, "rgba(134, 134, 134, 0.3)")]
    [InlineData(11, "rgba(156, 39, 176, .4)")]
    [InlineData(23, "rgba(220, 231, 117, 0.3)")]
    // JS % truncates toward zero (as does C#), so a negative index matches no case and lands
    // on the default color.
    [InlineData(-1, "rgba(229, 115, 155, 0.3)")]
    public void GetRgba_RoleIndex_ReturnsPaletteColor(int index, string expected)
    {
        Assert.Equal(expected, Colors.GetRgba(index));
    }

    [Theory]
    [InlineData("Recipient 1", "rgba(118, 200, 8, 0.2)")]
    [InlineData("Recipient 2", "rgba(39, 131, 8, 0.2)")]
    [InlineData("Owner", "rgba(131, 61, 8, 0.2)")]
    [InlineData("Approver", "rgba(58, 234, 8, 0.2)")]
    [InlineData("Signer", "rgba(158, 30, 0, 0.2)")]
    [InlineData("A", "rgba(0, 0, 0, 0.2)")]
    [InlineData("Role 10", "rgba(190, 120, 0, 0.2)")]
    [InlineData("countersigner", "rgba(70, 67, 8, 0.2)")]
    public void NameToRgba_RoleName_ReturnsNodeParityColor(string name, string expected)
    {
        Assert.Equal(expected, Colors.NameToRgba(name));
    }

    [Fact]
    public void NameToRgba_SameName_IsStable()
    {
        Assert.Equal(Colors.NameToRgba("Recipient 1"), Colors.NameToRgba("Recipient 1"));
    }

    [Fact]
    public void NameToRgba_EmptyName_ReturnsNull()
    {
        // The js-sdk implicitly returns undefined for a falsy name.
        Assert.Null(Colors.NameToRgba(""));
        Assert.Null(Colors.NameToRgba(null));
    }

    [Fact]
    public void GetRoleColor_ExplicitIndex_WinsOverRoles()
    {
        Assert.Equal("rgba(220, 231, 117, 0.3)", Colors.GetRoleColor("Owner", [], 3));
    }

    [Fact]
    public void GetRoleColor_IndexZero_FallsThroughToRolesLookup()
    {
        // js checks `if (index)`, so 0 is treated as absent and the roles lookup answers
        // instead. Quirk kept.
        Assert.Equal("rgba(255, 193, 7, 0.4)", Colors.GetRoleColor("Recipient 1", ["Recipient 1"], 0));
    }

    [Fact]
    public void GetRoleColor_NameInRoles_UsesPosition()
    {
        IReadOnlyList<string> roles = ["Recipient 1", "Recipient 2"];
        Assert.Equal("rgba(255, 193, 7, 0.4)", Colors.GetRoleColor("Recipient 1", roles));
        Assert.Equal("rgba(156, 39, 176, .4)", Colors.GetRoleColor("Recipient 2", roles));
    }

    [Fact]
    public void GetRoleColor_NameNotInRoles_FallsBackToNameHash()
    {
        Assert.Equal("rgba(91, 157, 8, 0.2)", Colors.GetRoleColor("Missing", ["Recipient 1"]));
        Assert.Equal("rgba(131, 61, 8, 0.2)", Colors.GetRoleColor("Owner", []));
        Assert.Equal("rgba(131, 61, 8, 0.2)", Colors.GetRoleColor("Owner", null));
    }
}
