name: Conformance

on:
  pull_request:
    branches: [main]

jobs:
  js-sdk:
    name: JS SDK Conformance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Conformance Test (JS SDK)
        env:
          VERDOCS_API_BASE: ${{ secrets.VERDOCS_CONFORMANCE_API_BASE }}
          VERDOCS_TEST_EMAIL: ${{ secrets.VERDOCS_CONFORMANCE_EMAIL }}
          VERDOCS_TEST_PASSWORD: ${{ secrets.VERDOCS_CONFORMANCE_PASSWORD }}
        run: pnpm --filter @verdocs/conformance run conformance
